[package]
name = "concurrent_qs"
version = "0.3.2"
edition = "2021"

[dependencies]
loom = { version = "0.6", features = ["checkpoint"], optional = true }

[features]
hl-loom = ["loom"]
full-loom = ["hl-loom"]

# this profile is meant for the hl-loom feature
[profile.loom]
inherits = "release"
opt-level = 3
lto = "thin"
debug = true
debug-assertions = true
overflow-checks = true